FROM ustwo/nodejs:4.1.1
MAINTAINER Davide Petrillo <davide@ustwo.com>

ENV NODE_PATH /home/ustwo/src

COPY package.sandbox.json /home/ustwo/package.json
RUN npm install --production
COPY src /home/ustwo/src
RUN mkdir -p /home/ustwo/public

EXPOSE 8889

CMD ["node", "./node_modules/babel/lib/_babel-node", "src/server/index.sandbox.js"]
