FROM node:4.1.1

MAINTAINER Nick Collings <nick@ustwo.com>

ENV TERM=xterm-256color \
    NODE_ENV=production

WORKDIR /usr/local/src

COPY compiler.json /usr/local/src/package.json
RUN npm install
RUN mkdir -p /usr/local/src/public

ENV PATH $PATH:/usr/local/src/node_modules/.bin

COPY gulpfile.babel.js /usr/local/src/gulpfile.babel.js
COPY src /usr/local/src/src

CMD ["npm", "run", "compile"]
