FROM ustwo/nodejs:4.1.1
MAINTAINER Davide Petrillo <davide@ustwo.com>

COPY package.sandbox.json /home/ustwo/package.json
RUN npm install --production
COPY src /home/ustwo/src
#COPY src/server/index.sandbox.js /home/ustwo/src/server/index.js
RUN mkdir -p /home/ustwo/public

CMD ["node", "./node_modules/babel/lib/_babel-node", "--optional", "es7.classProperties", "src/server/index.sandbox.js"]
