FROM busybox
MAINTAINER Arnau Siches <arnau@ustwo.com>

# Contains all secrets for the proxy to run properly

COPY etc/nginx/nginx.conf /etc/nginx/nginx.conf
COPY etc/nginx/mime.types /etc/nginx/mime.types
COPY etc/nginx/ssl.conf /etc/nginx/ssl.conf
COPY etc/nginx/conf.d/default.conf /etc/nginx/conf.d/default.conf
COPY etc/nginx/ssl /etc/nginx/ssl

VOLUME /etc/nginx
