FROM nginx

MAINTAINER Arnau Siches <arnau@ustwo.com>

ENV TERM=xterm-256color

COPY etc/nginx/nginx.conf /etc/nginx/nginx.conf
COPY etc/nginx/ssl.conf /etc/nginx/ssl.conf
COPY etc/nginx/conf.d/production.conf /etc/nginx/conf.d/default.conf
COPY etc/nginx/ssl /etc/nginx/ssl
COPY share/nginx/html /usr/share/nginx/html
COPY share/nginx/public /usr/share/nginx/assets
