FROM busybox
MAINTAINER Arnau Siches <arnau@ustwo.com>

# Contains all secrets for the proxy to run properly

COPY etc/nginx/ssl /etc/nginx/ssl
COPY etc/nginx/locations /etc/nginx/locations

VOLUME /etc/nginx/ssl

CMD ["true"]
